### ISSUE TITLE
[Bug]: Date Invisible in Light Mode on Event Calendar

### ISSUE THREAD

**Issue by Sailesh-Singh** [GNOME-Nepal/website#77]
### 📜 Description

Description
The event calendar on the GNOME Nepal site has a visibility issue where the dates are not visible in light mode but appear correctly in dark mode. This impacts the usability of the calendar, especially for users who prefer light mode.

### 👟 Reproduction steps

1. Navigate to the GNOME Nepal site and view the event calendar.
2. Switch to light mode.
3. Observe that the dates are not visible.
4. Switch to dark mode.
5. Observe that the dates appear correctly.

### 👍 Expected behavior

**Expected Behavior:**
The dates should be visible and legible in both light and dark modes.

### 👎 Actual Behavior with Screenshots

**Actual Behavior:**
The dates are invisible in light mode, making it difficult to use the calendar effectively.

![Invisible in Lightmode](https://github.com/user-attachments/assets/7d82d51b-919a-4b58-9b19-d349d2c091ff)

### 💻 Operating system

Linux

### 📃 Provide any additional context for the Bug.

**Proposed Solution:**
Update the calendar's CSS to ensure the text color of the dates contrasts sufficiently with the background in both light and dark modes.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utsavdotdev** [comment]
Solved in #76 by @bikashmishraa

**Comment by Sailesh-Singh** [comment]
Bug is still there In light mode:
![image](https://github.com/user-attachments/assets/09579188-9051-4036-91b1-443502e2dea3)

**Comment by Sailesh-Singh** [comment]
Okay, I didn't see that rather making the text plain black can we put just gray shade to give matte look.

![image](https://github.com/user-attachments/assets/3290c0f6-5988-4242-a01c-c9f83aaa2c7d)

**Comment by utsavdotdev** [comment]
Resolved
Checkout: https://nepal.gnome.org
